CI: Split build and run into two actions (#136)
## Description

Github actions have log limits of about 65K. This results in the loss
of visual logs in the workflow (The logs in the log file still exist).
To help combat this, we separate the setup & build from the run command
so that each action has it's own 65KB of logging available. This results
in all logging being visible without needing to download the uploaded
log files

Additionally, this commit updates the action to no longer publish the
logs,
but instead returns an output value (`log-path`) that callers of the
action can
use. In our case, we publish the logs.

Finally, this commit updates the action to no longer take a `flash`
argument,
but instead takes a `command` argument, which can be `build`, `flash`,
or `all`.

- [ ] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

CI

## Integration Instructions

N/A

diff --git a/.github/actions/build-platform/action.yml b/.github/actions/build-platform/action.yml
--- a/.github/actions/build-platform/action.yml
+++ b/.github/actions/build-platform/action.yml
@@ -9,6 +9,10 @@ name: Build QEMU Platform Firmware
 description: Build a QEMU platform firmware using Stuart
 
 inputs:
+  command:
+    description: 'The action to perform: `build`, `flash`, or `all`'
+    required: false
+    default: 'all'
   platform-config:
     description: 'Path to the Stuart platform configuration file (.py)'
     required: true
@@ -31,31 +35,39 @@ inputs:
     description: 'Additional build arguments to pass to stuart_build'
     required: false
     default: ''
-  flash:
-    description: 'Whether to flash the built platform firmware image (if supported)'
+  log-identifier:
+    description: 'Extra identifier to append to the log folder name if needed.'
     required: false
-    default: 'false'
-  publish-logs:
-    description: 'Whether to publish build logs'
-    required: false
-    default: 'false'
+    default: ''
+
+outputs:
+  log-path:
+    description: 'Path to the folder containing the build logs'
+    value: ${{ steps.tempdir.outputs.path}}
 
 runs:
   using: composite
 
   steps:
-  # Optional: Create a temporary directory for logs if publish-logs is true
+  - name: Validate command
+    id: validate
+    shell: bash
+    run: |
+      if [[ "${{ inputs.command }}" != "build" && "${{ inputs.command }}" != "flash" && "${{ inputs.command }}" != "all" ]]; then
+        echo "Invalid command: ${{ inputs.command }}. Must be one of: build, flash, all."
+        exit 1
+      fi
+
   - name: Create Temporary Directory
     id: tempdir
     shell: bash
     run: |
-      # if publish-logs is true, create a temp dir to capture logs
-      if [ "${{ inputs.publish-logs }}" != "false" ]; then
-        mkdir -p "$RUNNER_TEMP"/build-logs
-        echo "path="$RUNNER_TEMP"/build-logs" >> $GITHUB_OUTPUT
-      else
-        echo "path=" >> $GITHUB_OUTPUT
+      LOG_FOLDER_NAME="build-logs"
+      if [ -n "${{ inputs.log-identifier }}" ]; then
+        LOG_FOLDER_NAME="${LOG_FOLDER_NAME}-${{ inputs.log-identifier }}"
       fi
+      mkdir -p "$RUNNER_TEMP"/$LOG_FOLDER_NAME
+      echo "path="$RUNNER_TEMP"/$LOG_FOLDER_NAME" >> $GITHUB_OUTPUT
 
   # Cannot use ENV in a composite action, so lets create our reusable argument string here
   - name: Setup Total Stuart arguments
@@ -75,6 +87,7 @@ runs:
   
   # Use the cache key to attempt to restore cached submodules
   - name: Cache submodules
+    if: ${{ inputs.command == 'all' || inputs.command == 'build' }}
     uses: actions/cache@v4
     with:
       path: .git/modules
@@ -82,50 +95,66 @@ runs:
 
   # Stuart setup should be slightly faster if we were able to restore the cache to .git/modules
   - name: Download required submodules (stuart_setup)
+    if: ${{ inputs.command == 'all' || inputs.command == 'build' }}
     shell: bash
     run: |
       stuart_setup -c ${{ inputs.platform-config }} ${{ steps.stuart.outputs.arguments }}
   
-  # Optional: Move the setup log to the temporary directory if it was created
   - name: Move setup log
-    if: ${{ always() && steps.tempdir.outputs.path }}
+    if: always()
     shell: bash
     env:
       TEMP_DIR: ${{ steps.tempdir.outputs.path }}
     run: |
-      mv Build/SETUP*.txt "$TEMP_DIR"
+      shopt -s globstar nullglob
+      files=(Build/SETUP*.txt)
+
+      if ((${#files[@]})); then
+        echo "Moving ${#files[@]} log files"
+        mv "${files[@]}" "$TEMP_DIR"
+      else
+        echo "No matching log files found"
+      fi
 
   # Download external dependencies
   - name: Download external dependencies (stuart_update)
+    if: ${{ inputs.command == 'all' || inputs.command == 'build' }}
     shell: bash
     run: |
       stuart_update -c ${{ inputs.platform-config }} ${{ steps.stuart.outputs.arguments }}
   
-  # Optional: Move the update log to the temporary directory if it was created
   - name: Move update log
-    if: ${{ always() && steps.tempdir.outputs.path }}
+    if: always()
     shell: bash
     env:
       TEMP_DIR: ${{ steps.tempdir.outputs.path }}
     run: |
-      mv Build/UPDATE*.txt "$TEMP_DIR"
+      shopt -s globstar nullglob
+      files=(Build/UPDATE*.txt)
+
+      if ((${#files[@]})); then
+        echo "Moving ${#files[@]} log files"
+        mv "${files[@]}" "$TEMP_DIR"
+      else
+        echo "No matching log files found"
+      fi
   
   # Build the platform, specify architecture if it is not empty
   - name: Build platform (stuart_build)
+    if: ${{ inputs.command == 'all' || inputs.command == 'build' }}
     shell: bash
     run: |
       stuart_build -c ${{ inputs.platform-config }} ${{ steps.stuart.outputs.arguments }} \
       $([[ -n "${{ inputs.architecture }}" ]] && echo " -a ${{ inputs.architecture }}")
   
-  # Optional: Move the build logs to the temporary directory if it was created
   - name: Move build log
-    if: ${{ always() && steps.tempdir.outputs.path }}
+    if: always()
     shell: bash
     env:
       TEMP_DIR: ${{ steps.tempdir.outputs.path }}
     run: |
       shopt -s globstar nullglob
-      files=(**/BUILDLOG* **/BUILD_REPORT.TXT **/OVERRIDELOG.TXT)
+      files=(Build/**/BUILDLOG* Build/**/BUILD_REPORT.TXT Build/**/OVERRIDELOG.TXT)
 
       if ((${#files[@]})); then
         echo "Moving ${#files[@]} log files"
@@ -134,23 +163,21 @@ runs:
         echo "No matching log files found"
       fi
   
-  # Optional: Flash the platform if requested
   - name: Flash platform (stuart_build --FLASHONLY)
-    if: ${{ inputs.flash != 'false' }}
+    if: ${{ inputs.command == 'all' || inputs.command == 'flash' }}
     shell: bash
     run: |
       stuart_build -c ${{ inputs.platform-config }} --FLASHONLY ${{ steps.stuart.outputs.arguments }} \
       $([[ -n "${{ inputs.architecture }}" ]] && echo " -a ${{ inputs.architecture }}")
 
-  # Optional: Move the run logs to the temporary directory if it was created
   - name: Move run log
-    if: ${{ always() && inputs.flash && steps.tempdir.outputs.path }}
+    if: always()
     shell: bash
     env:
       TEMP_DIR: ${{ steps.tempdir.outputs.path }}
     run: |
       shopt -s globstar nullglob
-      files=(**/*Run.txt)
+      files=(Build/**/*Run.txt)
 
       if ((${#files[@]})); then
         echo "Moving ${#files[@]} log files"
@@ -158,12 +185,3 @@ runs:
       else
         echo "No matching log files found"
       fi
-
-  # Optional: Publish the logs as an artifact if the temporary directory was created
-  - name: Publish Logs
-    if: ${{ always() && steps.tempdir.outputs.path }}
-    uses: actions/upload-artifact@v4
-    with:
-      # Specify architecture if it is not empty
-      name: build-logs-${{ inputs.platform-name }}-${{ inputs.target }}-${{ inputs.tool-chain }}${{ inputs.architecture && format('-{0}', inputs.architecture) || '' }}
-      path: ${{ steps.tempdir.outputs.path }}
